### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by root9464** [VolodumurSN/React-Portfolio#4]
It doesn't work. I deployed your project in vs to look at the code for the sake of my interest, as a result I got about 80+ errors in the terminal

**Comment by vsnaichuk** [comment]
Hi! Could you provide an errors log?

**Comment by xuanchinh97** [comment]
I get npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name ">=^16.0.0" of package "react@>=^16.0.0": Tags may not have any characters that encodeURIComponent encodes.

I can't fix

**Comment by vsnaichuk** [comment]
@xuanchinh97 try

`npm install --legacy-peer-deps`

What npm version are you using?

**Comment by xuanchinh97** [comment]
I used Node version v17 at first, then I used Node version v16, npm version  8.1.2

npm install --legacy-peer-deps
npx browserslist@latest --update-db
npm install caniuse-lite
 npm audit fix
 npm audit fix --force
npm start 

it work for me
